# Generated by Django 5.0.6 on 2024-06-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrez_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastaFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrez_api.sequencerecord')),
            ],
        ),
    ]
