# Generated by Django 5.0.6 on 2024-06-05 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceFeatureLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.TextField()),
                ('ref_db', models.TextField()),
                ('strand', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SequenceFeature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('qualifiers', models.JSONField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrez_api.sequencefeaturelocation')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceRecord',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('seq', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('dbxrefs', models.JSONField()),
                ('annotations', models.JSONField()),
                ('letter_annotations', models.JSONField()),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrez_api.sequencefeature')),
            ],
        ),
    ]
