# Generated by Django 5.0.6 on 2024-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrez_api', '0004_alter_sequencerecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
