# Generated by Django 5.0.6 on 2024-06-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrez_api', '0005_alter_sequencerecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencerecord',
            name='annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencerecord',
            name='dbxrefs',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencerecord',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencerecord',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrez_api.sequencefeature'),
        ),
        migrations.AlterField(
            model_name='sequencerecord',
            name='letter_annotations',
            field=models.JSONField(null=True),
        ),
    ]
