# Generated by Django 5.0.6 on 2024-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrez_api', '0006_alter_sequencerecord_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencerecord',
            name='biopython_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencerecord',
            name='description',
            field=models.TextField(blank=True, default='no desc'),
            preserve_default=False,
        ),
    ]
